### ISSUE TITLE
bot management

### ISSUE THREAD

**Issue by 3ll060** [3ll060/fenrisNET#3]
Maybe use a database instead of a file

**Comment by FRosner** [comment]
Use one file per bot. It is lightweight and avoids write locks when multiple bots answer at the same time.

**Comment by 3ll060** [comment]
@FRosner Thank you for this hin!

**Comment by 3ll060** [comment]
Done.

**Comment by FRosner** [comment]
@3ll060 does it work? How is the performance compared to the SQLite solution? Did you try with 1000 bots?

**Comment by 3ll060** [comment]
@FRosner Yes it works. Compared to the SQLite solution the performance is really good. no visible "lock-problems".
I wrote a little python script which simulates a lot bot connections. The performance decreases obove 8000-10000 bots.
